apiVersion: apps/v1
kind: Deployment
metadata:
  name: adbping-test-v1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adbping-test-v1
  template:
    metadata:
      labels:
        app: adbping-test-v1
    spec:
      containers:
      - name: adbping
        image: odaamh.azurecr.io/adb-nettest:v1.0
        command: ["/bin/bash"]
        args: ["-c", "while true; do sleep 30; done;"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      restartPolicy: Always