apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include \"goldengate-da.fullname\" . }}"
  namespace: "{{ .Values.namespace | default .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ include \"goldengate-da.name\" . }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "Helm"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include \"goldengate-da.name\" . }}"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ include \"goldengate-da.name\" . }}"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      containers:
        - name: "goldengate-da"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          env:
            - name: "OGG_ADMIN"
              value: "{{ .Values.admin.user }}"
            - name: "OGG_ADMIN_PWD"
              valueFrom:
                secretKeyRef:
                  name: "{{ include \"goldengate-da.fullname\" . }}-credentials"
                  key: "OGG_ADMIN_PWD"
            - name: "OGG_DEPLOYMENT"
              value: "Local"
            - name: "OGG_LISTEN_ON"
              value: "0.0.0.0"
          ports:
            - name: "https"
              containerPort: {{ .Values.service.port }}
            - name: "http"
              containerPort: {{ .Values.service.httpPort }}
          volumeMounts:
            - name: "data"
              mountPath: "/u02"
            - name: "temp"
              mountPath: "/u03"
          resources:
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"
              memory: "{{ .Values.resources.limits.memory }}"
            requests:
              cpu: "{{ .Values.resources.requests.cpu }}"
              memory: "{{ .Values.resources.requests.memory }}"
      volumes:
        - name: "data"
          persistentVolumeClaim:
            claimName: "{{ include \"goldengate-da.fullname\" . }}-data"
        - name: "temp"
          emptyDir:
            medium: "Memory"
            sizeLimit: "{{ .Values.storage.temp.sizeLimit }}"
