apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ include \"goldengate-da.fullname\" . }}"
  namespace: "{{ .Values.namespace | default .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ include \"goldengate-da.name\" . }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingress.className }}"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: "{{ include \"goldengate-da.fullname\" . }}"
                port:
                  number: {{ .Values.service.port }}
