apiVersion: v1
kind: Secret
metadata:
  name: "{{ include \"goldengate-da.fullname\" . }}-credentials"
  namespace: "{{ .Values.namespace | default .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ include \"goldengate-da.name\" . }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "Helm"
type: Opaque
stringData:
  OGG_ADMIN_PWD: "{{ .Values.admin.password }}"
