apiVersion: v1
kind: Service
metadata:
  name: "{{ include \"goldengate-da.fullname\" . }}"
  namespace: "{{ .Values.namespace | default .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ include \"goldengate-da.name\" . }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "Helm"
spec:
  type: "{{ .Values.service.type }}"
  selector:
    app.kubernetes.io/name: "{{ include \"goldengate-da.name\" . }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
  ports:
    - name: "https"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
    - name: "http"
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
