apiVersion: apps/v1
kind: Deployment
metadata:
  name: adbping-deployment
  namespace: adb-perf-test
  labels:
    app: adbping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adbping
  template:
    metadata:
      labels:
        app: adbping
    spec:
      containers:
      - name: adbping
        image: odaamh.azurecr.io/adb-nettest:v2.1
        command: ["/bin/sleep"]
        args: ["3600"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: ORACLE_HOME
          value: "/usr/local/oracle"